//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Device_IP_History_Information
    {
        public string device_coding { get; set; }
        public string device_name { get; set; }
        public string ip { get; set; }
        public string ping_tag { get; set; }
        public System.DateTime ping_time { get; set; }
        public int id { get; set; }
    }
}
