//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_Device_IP_Information
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "主机名不可为空")]
        public string device_coding { get; set; }
        public string device_name { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "IP不可为空")]
        [RegularExpression(@"((?:(?:25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d)))\.){3}(?:25[0-5]|2[0-4]\d|((1\d{2})|([1-9]?\d))))\s*", ErrorMessage = "IP格式不正确！")]
        public string ip { get; set; }
        public string ping_tag { get; set; }
        public Nullable<System.DateTime> ping_time { get; set; }
        public int id { get; set; }
    }
}
